name: CD

on:
  push:
    branches:
      - main

jobs:
  CD:
    name: Continuos Delivery
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3